/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebhookEvolutionRouteImport } from './routes/webhook/evolution'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiPlansRouteImport } from './routes/api/plans'
import { Route as ApiMessagesRouteImport } from './routes/api/messages'
import { Route as ApiDashboardRouteImport } from './routes/api/dashboard'
import { Route as ApiConversationsRouteImport } from './routes/api/conversations'
import { Route as ApiContactsRouteImport } from './routes/api/contacts'
import { Route as ApiCompaniesRouteImport } from './routes/api/companies'
import { Route as ApiCampaignsRouteImport } from './routes/api/campaigns'
import { Route as ApiAttendantsRouteImport } from './routes/api/attendants'
import { Route as AppUsuariosRouteImport } from './routes/_app.usuarios'
import { Route as AppLogsRouteImport } from './routes/_app.logs'
import { Route as AppGruposInternosRouteImport } from './routes/_app.grupos-internos'
import { Route as AppEmpresasRouteImport } from './routes/_app.empresas'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppContatosRouteImport } from './routes/_app.contatos'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppComunicacaoInternaRouteImport } from './routes/_app.comunicacao-interna'
import { Route as AppCanaisRouteImport } from './routes/_app.canais'
import { Route as AppCampanhasRouteImport } from './routes/_app.campanhas'
import { Route as AppAutomacoesRouteImport } from './routes/_app.automacoes'
import { Route as AppAtendimentoRouteImport } from './routes/_app.atendimento'
import { Route as AppCampanhasIndexRouteImport } from './routes/_app.campanhas.index'
import { Route as ApiWebhooksMetaRouteImport } from './routes/api/webhooks/meta'
import { Route as ApiWebhooksEvolutionRouteImport } from './routes/api/webhooks/evolution'
import { Route as ApiUsersIdRouteImport } from './routes/api/users/$id'
import { Route as ApiMetaChannelsRouteImport } from './routes/api/meta/channels'
import { Route as ApiInternalChatUsersRouteImport } from './routes/api/internal-chat/users'
import { Route as ApiInternalChatUnreadCountRouteImport } from './routes/api/internal-chat/unread-count'
import { Route as ApiInternalChatSendRouteImport } from './routes/api/internal-chat/send'
import { Route as ApiInternalChatMessagesRouteImport } from './routes/api/internal-chat/messages'
import { Route as ApiInternalChatMarkReadRouteImport } from './routes/api/internal-chat/mark-read'
import { Route as ApiInternalChatListRouteImport } from './routes/api/internal-chat/list'
import { Route as ApiInternalChatCreateRouteImport } from './routes/api/internal-chat/create'
import { Route as ApiEvolutionStatusRouteImport } from './routes/api/evolution/status'
import { Route as ApiEvolutionSchemaCheckRouteImport } from './routes/api/evolution/schema-check'
import { Route as ApiEvolutionRegisterChannelRouteImport } from './routes/api/evolution/register-channel'
import { Route as ApiEvolutionChannelsRouteImport } from './routes/api/evolution/channels'
import { Route as ApiDebugPlansSelectsRouteImport } from './routes/api/debug/plans-selects'
import { Route as ApiDebugDbRouteImport } from './routes/api/debug/db'
import { Route as ApiDebugCurrentUserRouteImport } from './routes/api/debug/current-user'
import { Route as ApiDebugColsRouteImport } from './routes/api/debug/cols'
import { Route as ApiDashboardCampaignsRouteImport } from './routes/api/dashboard/campaigns'
import { Route as ApiConversationsStartRouteImport } from './routes/api/conversations/start'
import { Route as ApiContactsIdRouteImport } from './routes/api/contacts/$id'
import { Route as ApiCompaniesIdRouteImport } from './routes/api/companies/$id'
import { Route as ApiCampaignsIdRouteImport } from './routes/api/campaigns/$id'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthOperationalCompanyRouteImport } from './routes/api/auth/operational-company'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAttendanceNotificationsRouteImport } from './routes/api/attendance/notifications'
import { Route as ApiAdminSeedDemoRouteImport } from './routes/api/admin/seed-demo'
import { Route as ApiAdminResetPasswordRouteImport } from './routes/api/admin/reset-password'
import { Route as ApiAdminAuthCheckRouteImport } from './routes/api/admin/auth-check'
import { Route as AppCampanhasNovaRouteImport } from './routes/_app.campanhas.nova'
import { Route as AppCampanhasIdRouteImport } from './routes/_app.campanhas.$id'
import { Route as ApiWebhooksMetaWhatsappRouteImport } from './routes/api/webhooks/meta/whatsapp'
import { Route as ApiPublicWebhooksMetaRouteImport } from './routes/api/public/webhooks/meta'
import { Route as ApiPublicWebhooksEvolutionRouteImport } from './routes/api/public/webhooks/evolution'
import { Route as ApiMetaChannelsIdRouteImport } from './routes/api/meta/channels/$id'
import { Route as ApiMessagesSendEvolutionRouteImport } from './routes/api/messages/send/evolution'
import { Route as ApiMessagesMessageIdMediaRouteImport } from './routes/api/messages/$messageId/media'
import { Route as ApiEvolutionChannelsIdRouteImport } from './routes/api/evolution/channels/$id'
import { Route as ApiConversationsIdTransferRouteImport } from './routes/api/conversations/$id/transfer'
import { Route as ApiConversationsIdReadRouteImport } from './routes/api/conversations/$id/read'
import { Route as ApiConversationsIdMessagesRouteImport } from './routes/api/conversations/$id/messages'
import { Route as ApiConversationsIdAssumeRouteImport } from './routes/api/conversations/$id/assume'
import { Route as ApiCompaniesIdSubscriptionRouteImport } from './routes/api/companies/$id/subscription'
import { Route as ApiCampaignsWorkerTickRouteImport } from './routes/api/campaigns/worker/tick'
import { Route as ApiCampaignsIdScheduleRouteImport } from './routes/api/campaigns/$id/schedule'
import { Route as ApiCampaignsIdContactsRouteImport } from './routes/api/campaigns/$id/contacts'
import { Route as ApiMetaChannelsIdStatusRouteImport } from './routes/api/meta/channels/$id/status'
import { Route as ApiMessagesSendMediaEvolutionRouteImport } from './routes/api/messages/send/media/evolution'
import { Route as ApiInternalChatMessagesIdAttachmentRouteImport } from './routes/api/internal-chat/messages/$id/attachment'
import { Route as ApiEvolutionChannelsIdStatusRouteImport } from './routes/api/evolution/channels/$id/status'
import { Route as ApiEvolutionChannelsIdQrcodeRouteImport } from './routes/api/evolution/channels/$id/qrcode'
import { Route as ApiEvolutionChannelsIdDisconnectRouteImport } from './routes/api/evolution/channels/$id/disconnect'
import { Route as ApiEvolutionChannelsIdConnectRouteImport } from './routes/api/evolution/channels/$id/connect'
import { Route as ApiCampaignsIdContactsContactRowIdRouteImport } from './routes/api/campaigns/$id/contacts/$contactRowId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhookEvolutionRoute = WebhookEvolutionRouteImport.update({
  id: '/webhook/evolution',
  path: '/webhook/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlansRoute = ApiPlansRouteImport.update({
  id: '/api/plans',
  path: '/api/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesRoute = ApiMessagesRouteImport.update({
  id: '/api/messages',
  path: '/api/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardRoute = ApiDashboardRouteImport.update({
  id: '/api/dashboard',
  path: '/api/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsRoute = ApiConversationsRouteImport.update({
  id: '/api/conversations',
  path: '/api/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactsRoute = ApiContactsRouteImport.update({
  id: '/api/contacts',
  path: '/api/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompaniesRoute = ApiCompaniesRouteImport.update({
  id: '/api/companies',
  path: '/api/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsRoute = ApiCampaignsRouteImport.update({
  id: '/api/campaigns',
  path: '/api/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttendantsRoute = ApiAttendantsRouteImport.update({
  id: '/api/attendants',
  path: '/api/attendants',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppGruposInternosRoute = AppGruposInternosRouteImport.update({
  id: '/grupos-internos',
  path: '/grupos-internos',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresasRoute = AppEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContatosRoute = AppContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppComunicacaoInternaRoute = AppComunicacaoInternaRouteImport.update({
  id: '/comunicacao-interna',
  path: '/comunicacao-interna',
  getParentRoute: () => AppRoute,
} as any)
const AppCanaisRoute = AppCanaisRouteImport.update({
  id: '/canais',
  path: '/canais',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasRoute = AppCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomacoesRoute = AppAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAtendimentoRoute = AppAtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasIndexRoute = AppCampanhasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCampanhasRoute,
} as any)
const ApiWebhooksMetaRoute = ApiWebhooksMetaRouteImport.update({
  id: '/api/webhooks/meta',
  path: '/api/webhooks/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksEvolutionRoute = ApiWebhooksEvolutionRouteImport.update({
  id: '/api/webhooks/evolution',
  path: '/api/webhooks/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiMetaChannelsRoute = ApiMetaChannelsRouteImport.update({
  id: '/api/meta/channels',
  path: '/api/meta/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalChatUsersRoute = ApiInternalChatUsersRouteImport.update({
  id: '/api/internal-chat/users',
  path: '/api/internal-chat/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalChatUnreadCountRoute =
  ApiInternalChatUnreadCountRouteImport.update({
    id: '/api/internal-chat/unread-count',
    path: '/api/internal-chat/unread-count',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInternalChatSendRoute = ApiInternalChatSendRouteImport.update({
  id: '/api/internal-chat/send',
  path: '/api/internal-chat/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalChatMessagesRoute = ApiInternalChatMessagesRouteImport.update({
  id: '/api/internal-chat/messages',
  path: '/api/internal-chat/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalChatMarkReadRoute = ApiInternalChatMarkReadRouteImport.update({
  id: '/api/internal-chat/mark-read',
  path: '/api/internal-chat/mark-read',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalChatListRoute = ApiInternalChatListRouteImport.update({
  id: '/api/internal-chat/list',
  path: '/api/internal-chat/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalChatCreateRoute = ApiInternalChatCreateRouteImport.update({
  id: '/api/internal-chat/create',
  path: '/api/internal-chat/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvolutionStatusRoute = ApiEvolutionStatusRouteImport.update({
  id: '/api/evolution/status',
  path: '/api/evolution/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvolutionSchemaCheckRoute = ApiEvolutionSchemaCheckRouteImport.update({
  id: '/api/evolution/schema-check',
  path: '/api/evolution/schema-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvolutionRegisterChannelRoute =
  ApiEvolutionRegisterChannelRouteImport.update({
    id: '/api/evolution/register-channel',
    path: '/api/evolution/register-channel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEvolutionChannelsRoute = ApiEvolutionChannelsRouteImport.update({
  id: '/api/evolution/channels',
  path: '/api/evolution/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugPlansSelectsRoute = ApiDebugPlansSelectsRouteImport.update({
  id: '/api/debug/plans-selects',
  path: '/api/debug/plans-selects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugDbRoute = ApiDebugDbRouteImport.update({
  id: '/api/debug/db',
  path: '/api/debug/db',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugCurrentUserRoute = ApiDebugCurrentUserRouteImport.update({
  id: '/api/debug/current-user',
  path: '/api/debug/current-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugColsRoute = ApiDebugColsRouteImport.update({
  id: '/api/debug/cols',
  path: '/api/debug/cols',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardCampaignsRoute = ApiDashboardCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => ApiDashboardRoute,
} as any)
const ApiConversationsStartRoute = ApiConversationsStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => ApiConversationsRoute,
} as any)
const ApiContactsIdRoute = ApiContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiContactsRoute,
} as any)
const ApiCompaniesIdRoute = ApiCompaniesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCompaniesRoute,
} as any)
const ApiCampaignsIdRoute = ApiCampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCampaignsRoute,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthOperationalCompanyRoute =
  ApiAuthOperationalCompanyRouteImport.update({
    id: '/api/auth/operational-company',
    path: '/api/auth/operational-company',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttendanceNotificationsRoute =
  ApiAttendanceNotificationsRouteImport.update({
    id: '/api/attendance/notifications',
    path: '/api/attendance/notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminSeedDemoRoute = ApiAdminSeedDemoRouteImport.update({
  id: '/api/admin/seed-demo',
  path: '/api/admin/seed-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminResetPasswordRoute = ApiAdminResetPasswordRouteImport.update({
  id: '/api/admin/reset-password',
  path: '/api/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthCheckRoute = ApiAdminAuthCheckRouteImport.update({
  id: '/api/admin/auth-check',
  path: '/api/admin/auth-check',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCampanhasNovaRoute = AppCampanhasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AppCampanhasRoute,
} as any)
const AppCampanhasIdRoute = AppCampanhasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCampanhasRoute,
} as any)
const ApiWebhooksMetaWhatsappRoute = ApiWebhooksMetaWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => ApiWebhooksMetaRoute,
} as any)
const ApiPublicWebhooksMetaRoute = ApiPublicWebhooksMetaRouteImport.update({
  id: '/api/public/webhooks/meta',
  path: '/api/public/webhooks/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksEvolutionRoute =
  ApiPublicWebhooksEvolutionRouteImport.update({
    id: '/api/public/webhooks/evolution',
    path: '/api/public/webhooks/evolution',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMetaChannelsIdRoute = ApiMetaChannelsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMetaChannelsRoute,
} as any)
const ApiMessagesSendEvolutionRoute =
  ApiMessagesSendEvolutionRouteImport.update({
    id: '/send/evolution',
    path: '/send/evolution',
    getParentRoute: () => ApiMessagesRoute,
  } as any)
const ApiMessagesMessageIdMediaRoute =
  ApiMessagesMessageIdMediaRouteImport.update({
    id: '/$messageId/media',
    path: '/$messageId/media',
    getParentRoute: () => ApiMessagesRoute,
  } as any)
const ApiEvolutionChannelsIdRoute = ApiEvolutionChannelsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiEvolutionChannelsRoute,
} as any)
const ApiConversationsIdTransferRoute =
  ApiConversationsIdTransferRouteImport.update({
    id: '/$id/transfer',
    path: '/$id/transfer',
    getParentRoute: () => ApiConversationsRoute,
  } as any)
const ApiConversationsIdReadRoute = ApiConversationsIdReadRouteImport.update({
  id: '/$id/read',
  path: '/$id/read',
  getParentRoute: () => ApiConversationsRoute,
} as any)
const ApiConversationsIdMessagesRoute =
  ApiConversationsIdMessagesRouteImport.update({
    id: '/$id/messages',
    path: '/$id/messages',
    getParentRoute: () => ApiConversationsRoute,
  } as any)
const ApiConversationsIdAssumeRoute =
  ApiConversationsIdAssumeRouteImport.update({
    id: '/$id/assume',
    path: '/$id/assume',
    getParentRoute: () => ApiConversationsRoute,
  } as any)
const ApiCompaniesIdSubscriptionRoute =
  ApiCompaniesIdSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => ApiCompaniesIdRoute,
  } as any)
const ApiCampaignsWorkerTickRoute = ApiCampaignsWorkerTickRouteImport.update({
  id: '/worker/tick',
  path: '/worker/tick',
  getParentRoute: () => ApiCampaignsRoute,
} as any)
const ApiCampaignsIdScheduleRoute = ApiCampaignsIdScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ApiCampaignsIdRoute,
} as any)
const ApiCampaignsIdContactsRoute = ApiCampaignsIdContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => ApiCampaignsIdRoute,
} as any)
const ApiMetaChannelsIdStatusRoute = ApiMetaChannelsIdStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiMetaChannelsIdRoute,
} as any)
const ApiMessagesSendMediaEvolutionRoute =
  ApiMessagesSendMediaEvolutionRouteImport.update({
    id: '/send/media/evolution',
    path: '/send/media/evolution',
    getParentRoute: () => ApiMessagesRoute,
  } as any)
const ApiInternalChatMessagesIdAttachmentRoute =
  ApiInternalChatMessagesIdAttachmentRouteImport.update({
    id: '/$id/attachment',
    path: '/$id/attachment',
    getParentRoute: () => ApiInternalChatMessagesRoute,
  } as any)
const ApiEvolutionChannelsIdStatusRoute =
  ApiEvolutionChannelsIdStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => ApiEvolutionChannelsIdRoute,
  } as any)
const ApiEvolutionChannelsIdQrcodeRoute =
  ApiEvolutionChannelsIdQrcodeRouteImport.update({
    id: '/qrcode',
    path: '/qrcode',
    getParentRoute: () => ApiEvolutionChannelsIdRoute,
  } as any)
const ApiEvolutionChannelsIdDisconnectRoute =
  ApiEvolutionChannelsIdDisconnectRouteImport.update({
    id: '/disconnect',
    path: '/disconnect',
    getParentRoute: () => ApiEvolutionChannelsIdRoute,
  } as any)
const ApiEvolutionChannelsIdConnectRoute =
  ApiEvolutionChannelsIdConnectRouteImport.update({
    id: '/connect',
    path: '/connect',
    getParentRoute: () => ApiEvolutionChannelsIdRoute,
  } as any)
const ApiCampaignsIdContactsContactRowIdRoute =
  ApiCampaignsIdContactsContactRowIdRouteImport.update({
    id: '/$contactRowId',
    path: '/$contactRowId',
    getParentRoute: () => ApiCampaignsIdContactsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/atendimento': typeof AppAtendimentoRoute
  '/automacoes': typeof AppAutomacoesRoute
  '/campanhas': typeof AppCampanhasRouteWithChildren
  '/canais': typeof AppCanaisRoute
  '/comunicacao-interna': typeof AppComunicacaoInternaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contatos': typeof AppContatosRoute
  '/dashboard': typeof AppDashboardRoute
  '/empresas': typeof AppEmpresasRoute
  '/grupos-internos': typeof AppGruposInternosRoute
  '/logs': typeof AppLogsRoute
  '/usuarios': typeof AppUsuariosRoute
  '/api/attendants': typeof ApiAttendantsRoute
  '/api/campaigns': typeof ApiCampaignsRouteWithChildren
  '/api/companies': typeof ApiCompaniesRouteWithChildren
  '/api/contacts': typeof ApiContactsRouteWithChildren
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRouteWithChildren
  '/api/messages': typeof ApiMessagesRouteWithChildren
  '/api/plans': typeof ApiPlansRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/webhook/evolution': typeof WebhookEvolutionRoute
  '/campanhas/$id': typeof AppCampanhasIdRoute
  '/campanhas/nova': typeof AppCampanhasNovaRoute
  '/api/admin/auth-check': typeof ApiAdminAuthCheckRoute
  '/api/admin/reset-password': typeof ApiAdminResetPasswordRoute
  '/api/admin/seed-demo': typeof ApiAdminSeedDemoRoute
  '/api/attendance/notifications': typeof ApiAttendanceNotificationsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/operational-company': typeof ApiAuthOperationalCompanyRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/campaigns/$id': typeof ApiCampaignsIdRouteWithChildren
  '/api/companies/$id': typeof ApiCompaniesIdRouteWithChildren
  '/api/contacts/$id': typeof ApiContactsIdRoute
  '/api/conversations/start': typeof ApiConversationsStartRoute
  '/api/dashboard/campaigns': typeof ApiDashboardCampaignsRoute
  '/api/debug/cols': typeof ApiDebugColsRoute
  '/api/debug/current-user': typeof ApiDebugCurrentUserRoute
  '/api/debug/db': typeof ApiDebugDbRoute
  '/api/debug/plans-selects': typeof ApiDebugPlansSelectsRoute
  '/api/evolution/channels': typeof ApiEvolutionChannelsRouteWithChildren
  '/api/evolution/register-channel': typeof ApiEvolutionRegisterChannelRoute
  '/api/evolution/schema-check': typeof ApiEvolutionSchemaCheckRoute
  '/api/evolution/status': typeof ApiEvolutionStatusRoute
  '/api/internal-chat/create': typeof ApiInternalChatCreateRoute
  '/api/internal-chat/list': typeof ApiInternalChatListRoute
  '/api/internal-chat/mark-read': typeof ApiInternalChatMarkReadRoute
  '/api/internal-chat/messages': typeof ApiInternalChatMessagesRouteWithChildren
  '/api/internal-chat/send': typeof ApiInternalChatSendRoute
  '/api/internal-chat/unread-count': typeof ApiInternalChatUnreadCountRoute
  '/api/internal-chat/users': typeof ApiInternalChatUsersRoute
  '/api/meta/channels': typeof ApiMetaChannelsRouteWithChildren
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/webhooks/evolution': typeof ApiWebhooksEvolutionRoute
  '/api/webhooks/meta': typeof ApiWebhooksMetaRouteWithChildren
  '/campanhas/': typeof AppCampanhasIndexRoute
  '/api/campaigns/$id/contacts': typeof ApiCampaignsIdContactsRouteWithChildren
  '/api/campaigns/$id/schedule': typeof ApiCampaignsIdScheduleRoute
  '/api/campaigns/worker/tick': typeof ApiCampaignsWorkerTickRoute
  '/api/companies/$id/subscription': typeof ApiCompaniesIdSubscriptionRoute
  '/api/conversations/$id/assume': typeof ApiConversationsIdAssumeRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
  '/api/conversations/$id/read': typeof ApiConversationsIdReadRoute
  '/api/conversations/$id/transfer': typeof ApiConversationsIdTransferRoute
  '/api/evolution/channels/$id': typeof ApiEvolutionChannelsIdRouteWithChildren
  '/api/messages/$messageId/media': typeof ApiMessagesMessageIdMediaRoute
  '/api/messages/send/evolution': typeof ApiMessagesSendEvolutionRoute
  '/api/meta/channels/$id': typeof ApiMetaChannelsIdRouteWithChildren
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRoute
  '/api/public/webhooks/meta': typeof ApiPublicWebhooksMetaRoute
  '/api/webhooks/meta/whatsapp': typeof ApiWebhooksMetaWhatsappRoute
  '/api/campaigns/$id/contacts/$contactRowId': typeof ApiCampaignsIdContactsContactRowIdRoute
  '/api/evolution/channels/$id/connect': typeof ApiEvolutionChannelsIdConnectRoute
  '/api/evolution/channels/$id/disconnect': typeof ApiEvolutionChannelsIdDisconnectRoute
  '/api/evolution/channels/$id/qrcode': typeof ApiEvolutionChannelsIdQrcodeRoute
  '/api/evolution/channels/$id/status': typeof ApiEvolutionChannelsIdStatusRoute
  '/api/internal-chat/messages/$id/attachment': typeof ApiInternalChatMessagesIdAttachmentRoute
  '/api/messages/send/media/evolution': typeof ApiMessagesSendMediaEvolutionRoute
  '/api/meta/channels/$id/status': typeof ApiMetaChannelsIdStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/atendimento': typeof AppAtendimentoRoute
  '/automacoes': typeof AppAutomacoesRoute
  '/canais': typeof AppCanaisRoute
  '/comunicacao-interna': typeof AppComunicacaoInternaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contatos': typeof AppContatosRoute
  '/dashboard': typeof AppDashboardRoute
  '/empresas': typeof AppEmpresasRoute
  '/grupos-internos': typeof AppGruposInternosRoute
  '/logs': typeof AppLogsRoute
  '/usuarios': typeof AppUsuariosRoute
  '/api/attendants': typeof ApiAttendantsRoute
  '/api/campaigns': typeof ApiCampaignsRouteWithChildren
  '/api/companies': typeof ApiCompaniesRouteWithChildren
  '/api/contacts': typeof ApiContactsRouteWithChildren
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRouteWithChildren
  '/api/messages': typeof ApiMessagesRouteWithChildren
  '/api/plans': typeof ApiPlansRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/webhook/evolution': typeof WebhookEvolutionRoute
  '/campanhas/$id': typeof AppCampanhasIdRoute
  '/campanhas/nova': typeof AppCampanhasNovaRoute
  '/api/admin/auth-check': typeof ApiAdminAuthCheckRoute
  '/api/admin/reset-password': typeof ApiAdminResetPasswordRoute
  '/api/admin/seed-demo': typeof ApiAdminSeedDemoRoute
  '/api/attendance/notifications': typeof ApiAttendanceNotificationsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/operational-company': typeof ApiAuthOperationalCompanyRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/campaigns/$id': typeof ApiCampaignsIdRouteWithChildren
  '/api/companies/$id': typeof ApiCompaniesIdRouteWithChildren
  '/api/contacts/$id': typeof ApiContactsIdRoute
  '/api/conversations/start': typeof ApiConversationsStartRoute
  '/api/dashboard/campaigns': typeof ApiDashboardCampaignsRoute
  '/api/debug/cols': typeof ApiDebugColsRoute
  '/api/debug/current-user': typeof ApiDebugCurrentUserRoute
  '/api/debug/db': typeof ApiDebugDbRoute
  '/api/debug/plans-selects': typeof ApiDebugPlansSelectsRoute
  '/api/evolution/channels': typeof ApiEvolutionChannelsRouteWithChildren
  '/api/evolution/register-channel': typeof ApiEvolutionRegisterChannelRoute
  '/api/evolution/schema-check': typeof ApiEvolutionSchemaCheckRoute
  '/api/evolution/status': typeof ApiEvolutionStatusRoute
  '/api/internal-chat/create': typeof ApiInternalChatCreateRoute
  '/api/internal-chat/list': typeof ApiInternalChatListRoute
  '/api/internal-chat/mark-read': typeof ApiInternalChatMarkReadRoute
  '/api/internal-chat/messages': typeof ApiInternalChatMessagesRouteWithChildren
  '/api/internal-chat/send': typeof ApiInternalChatSendRoute
  '/api/internal-chat/unread-count': typeof ApiInternalChatUnreadCountRoute
  '/api/internal-chat/users': typeof ApiInternalChatUsersRoute
  '/api/meta/channels': typeof ApiMetaChannelsRouteWithChildren
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/webhooks/evolution': typeof ApiWebhooksEvolutionRoute
  '/api/webhooks/meta': typeof ApiWebhooksMetaRouteWithChildren
  '/campanhas': typeof AppCampanhasIndexRoute
  '/api/campaigns/$id/contacts': typeof ApiCampaignsIdContactsRouteWithChildren
  '/api/campaigns/$id/schedule': typeof ApiCampaignsIdScheduleRoute
  '/api/campaigns/worker/tick': typeof ApiCampaignsWorkerTickRoute
  '/api/companies/$id/subscription': typeof ApiCompaniesIdSubscriptionRoute
  '/api/conversations/$id/assume': typeof ApiConversationsIdAssumeRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
  '/api/conversations/$id/read': typeof ApiConversationsIdReadRoute
  '/api/conversations/$id/transfer': typeof ApiConversationsIdTransferRoute
  '/api/evolution/channels/$id': typeof ApiEvolutionChannelsIdRouteWithChildren
  '/api/messages/$messageId/media': typeof ApiMessagesMessageIdMediaRoute
  '/api/messages/send/evolution': typeof ApiMessagesSendEvolutionRoute
  '/api/meta/channels/$id': typeof ApiMetaChannelsIdRouteWithChildren
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRoute
  '/api/public/webhooks/meta': typeof ApiPublicWebhooksMetaRoute
  '/api/webhooks/meta/whatsapp': typeof ApiWebhooksMetaWhatsappRoute
  '/api/campaigns/$id/contacts/$contactRowId': typeof ApiCampaignsIdContactsContactRowIdRoute
  '/api/evolution/channels/$id/connect': typeof ApiEvolutionChannelsIdConnectRoute
  '/api/evolution/channels/$id/disconnect': typeof ApiEvolutionChannelsIdDisconnectRoute
  '/api/evolution/channels/$id/qrcode': typeof ApiEvolutionChannelsIdQrcodeRoute
  '/api/evolution/channels/$id/status': typeof ApiEvolutionChannelsIdStatusRoute
  '/api/internal-chat/messages/$id/attachment': typeof ApiInternalChatMessagesIdAttachmentRoute
  '/api/messages/send/media/evolution': typeof ApiMessagesSendMediaEvolutionRoute
  '/api/meta/channels/$id/status': typeof ApiMetaChannelsIdStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/atendimento': typeof AppAtendimentoRoute
  '/_app/automacoes': typeof AppAutomacoesRoute
  '/_app/campanhas': typeof AppCampanhasRouteWithChildren
  '/_app/canais': typeof AppCanaisRoute
  '/_app/comunicacao-interna': typeof AppComunicacaoInternaRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/contatos': typeof AppContatosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/empresas': typeof AppEmpresasRoute
  '/_app/grupos-internos': typeof AppGruposInternosRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/api/attendants': typeof ApiAttendantsRoute
  '/api/campaigns': typeof ApiCampaignsRouteWithChildren
  '/api/companies': typeof ApiCompaniesRouteWithChildren
  '/api/contacts': typeof ApiContactsRouteWithChildren
  '/api/conversations': typeof ApiConversationsRouteWithChildren
  '/api/dashboard': typeof ApiDashboardRouteWithChildren
  '/api/messages': typeof ApiMessagesRouteWithChildren
  '/api/plans': typeof ApiPlansRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/webhook/evolution': typeof WebhookEvolutionRoute
  '/_app/campanhas/$id': typeof AppCampanhasIdRoute
  '/_app/campanhas/nova': typeof AppCampanhasNovaRoute
  '/api/admin/auth-check': typeof ApiAdminAuthCheckRoute
  '/api/admin/reset-password': typeof ApiAdminResetPasswordRoute
  '/api/admin/seed-demo': typeof ApiAdminSeedDemoRoute
  '/api/attendance/notifications': typeof ApiAttendanceNotificationsRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/operational-company': typeof ApiAuthOperationalCompanyRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/campaigns/$id': typeof ApiCampaignsIdRouteWithChildren
  '/api/companies/$id': typeof ApiCompaniesIdRouteWithChildren
  '/api/contacts/$id': typeof ApiContactsIdRoute
  '/api/conversations/start': typeof ApiConversationsStartRoute
  '/api/dashboard/campaigns': typeof ApiDashboardCampaignsRoute
  '/api/debug/cols': typeof ApiDebugColsRoute
  '/api/debug/current-user': typeof ApiDebugCurrentUserRoute
  '/api/debug/db': typeof ApiDebugDbRoute
  '/api/debug/plans-selects': typeof ApiDebugPlansSelectsRoute
  '/api/evolution/channels': typeof ApiEvolutionChannelsRouteWithChildren
  '/api/evolution/register-channel': typeof ApiEvolutionRegisterChannelRoute
  '/api/evolution/schema-check': typeof ApiEvolutionSchemaCheckRoute
  '/api/evolution/status': typeof ApiEvolutionStatusRoute
  '/api/internal-chat/create': typeof ApiInternalChatCreateRoute
  '/api/internal-chat/list': typeof ApiInternalChatListRoute
  '/api/internal-chat/mark-read': typeof ApiInternalChatMarkReadRoute
  '/api/internal-chat/messages': typeof ApiInternalChatMessagesRouteWithChildren
  '/api/internal-chat/send': typeof ApiInternalChatSendRoute
  '/api/internal-chat/unread-count': typeof ApiInternalChatUnreadCountRoute
  '/api/internal-chat/users': typeof ApiInternalChatUsersRoute
  '/api/meta/channels': typeof ApiMetaChannelsRouteWithChildren
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/webhooks/evolution': typeof ApiWebhooksEvolutionRoute
  '/api/webhooks/meta': typeof ApiWebhooksMetaRouteWithChildren
  '/_app/campanhas/': typeof AppCampanhasIndexRoute
  '/api/campaigns/$id/contacts': typeof ApiCampaignsIdContactsRouteWithChildren
  '/api/campaigns/$id/schedule': typeof ApiCampaignsIdScheduleRoute
  '/api/campaigns/worker/tick': typeof ApiCampaignsWorkerTickRoute
  '/api/companies/$id/subscription': typeof ApiCompaniesIdSubscriptionRoute
  '/api/conversations/$id/assume': typeof ApiConversationsIdAssumeRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
  '/api/conversations/$id/read': typeof ApiConversationsIdReadRoute
  '/api/conversations/$id/transfer': typeof ApiConversationsIdTransferRoute
  '/api/evolution/channels/$id': typeof ApiEvolutionChannelsIdRouteWithChildren
  '/api/messages/$messageId/media': typeof ApiMessagesMessageIdMediaRoute
  '/api/messages/send/evolution': typeof ApiMessagesSendEvolutionRoute
  '/api/meta/channels/$id': typeof ApiMetaChannelsIdRouteWithChildren
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRoute
  '/api/public/webhooks/meta': typeof ApiPublicWebhooksMetaRoute
  '/api/webhooks/meta/whatsapp': typeof ApiWebhooksMetaWhatsappRoute
  '/api/campaigns/$id/contacts/$contactRowId': typeof ApiCampaignsIdContactsContactRowIdRoute
  '/api/evolution/channels/$id/connect': typeof ApiEvolutionChannelsIdConnectRoute
  '/api/evolution/channels/$id/disconnect': typeof ApiEvolutionChannelsIdDisconnectRoute
  '/api/evolution/channels/$id/qrcode': typeof ApiEvolutionChannelsIdQrcodeRoute
  '/api/evolution/channels/$id/status': typeof ApiEvolutionChannelsIdStatusRoute
  '/api/internal-chat/messages/$id/attachment': typeof ApiInternalChatMessagesIdAttachmentRoute
  '/api/messages/send/media/evolution': typeof ApiMessagesSendMediaEvolutionRoute
  '/api/meta/channels/$id/status': typeof ApiMetaChannelsIdStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/atendimento'
    | '/automacoes'
    | '/campanhas'
    | '/canais'
    | '/comunicacao-interna'
    | '/configuracoes'
    | '/contatos'
    | '/dashboard'
    | '/empresas'
    | '/grupos-internos'
    | '/logs'
    | '/usuarios'
    | '/api/attendants'
    | '/api/campaigns'
    | '/api/companies'
    | '/api/contacts'
    | '/api/conversations'
    | '/api/dashboard'
    | '/api/messages'
    | '/api/plans'
    | '/api/users'
    | '/webhook/evolution'
    | '/campanhas/$id'
    | '/campanhas/nova'
    | '/api/admin/auth-check'
    | '/api/admin/reset-password'
    | '/api/admin/seed-demo'
    | '/api/attendance/notifications'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/auth/operational-company'
    | '/api/auth/register'
    | '/api/campaigns/$id'
    | '/api/companies/$id'
    | '/api/contacts/$id'
    | '/api/conversations/start'
    | '/api/dashboard/campaigns'
    | '/api/debug/cols'
    | '/api/debug/current-user'
    | '/api/debug/db'
    | '/api/debug/plans-selects'
    | '/api/evolution/channels'
    | '/api/evolution/register-channel'
    | '/api/evolution/schema-check'
    | '/api/evolution/status'
    | '/api/internal-chat/create'
    | '/api/internal-chat/list'
    | '/api/internal-chat/mark-read'
    | '/api/internal-chat/messages'
    | '/api/internal-chat/send'
    | '/api/internal-chat/unread-count'
    | '/api/internal-chat/users'
    | '/api/meta/channels'
    | '/api/users/$id'
    | '/api/webhooks/evolution'
    | '/api/webhooks/meta'
    | '/campanhas/'
    | '/api/campaigns/$id/contacts'
    | '/api/campaigns/$id/schedule'
    | '/api/campaigns/worker/tick'
    | '/api/companies/$id/subscription'
    | '/api/conversations/$id/assume'
    | '/api/conversations/$id/messages'
    | '/api/conversations/$id/read'
    | '/api/conversations/$id/transfer'
    | '/api/evolution/channels/$id'
    | '/api/messages/$messageId/media'
    | '/api/messages/send/evolution'
    | '/api/meta/channels/$id'
    | '/api/public/webhooks/evolution'
    | '/api/public/webhooks/meta'
    | '/api/webhooks/meta/whatsapp'
    | '/api/campaigns/$id/contacts/$contactRowId'
    | '/api/evolution/channels/$id/connect'
    | '/api/evolution/channels/$id/disconnect'
    | '/api/evolution/channels/$id/qrcode'
    | '/api/evolution/channels/$id/status'
    | '/api/internal-chat/messages/$id/attachment'
    | '/api/messages/send/media/evolution'
    | '/api/meta/channels/$id/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/atendimento'
    | '/automacoes'
    | '/canais'
    | '/comunicacao-interna'
    | '/configuracoes'
    | '/contatos'
    | '/dashboard'
    | '/empresas'
    | '/grupos-internos'
    | '/logs'
    | '/usuarios'
    | '/api/attendants'
    | '/api/campaigns'
    | '/api/companies'
    | '/api/contacts'
    | '/api/conversations'
    | '/api/dashboard'
    | '/api/messages'
    | '/api/plans'
    | '/api/users'
    | '/webhook/evolution'
    | '/campanhas/$id'
    | '/campanhas/nova'
    | '/api/admin/auth-check'
    | '/api/admin/reset-password'
    | '/api/admin/seed-demo'
    | '/api/attendance/notifications'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/auth/operational-company'
    | '/api/auth/register'
    | '/api/campaigns/$id'
    | '/api/companies/$id'
    | '/api/contacts/$id'
    | '/api/conversations/start'
    | '/api/dashboard/campaigns'
    | '/api/debug/cols'
    | '/api/debug/current-user'
    | '/api/debug/db'
    | '/api/debug/plans-selects'
    | '/api/evolution/channels'
    | '/api/evolution/register-channel'
    | '/api/evolution/schema-check'
    | '/api/evolution/status'
    | '/api/internal-chat/create'
    | '/api/internal-chat/list'
    | '/api/internal-chat/mark-read'
    | '/api/internal-chat/messages'
    | '/api/internal-chat/send'
    | '/api/internal-chat/unread-count'
    | '/api/internal-chat/users'
    | '/api/meta/channels'
    | '/api/users/$id'
    | '/api/webhooks/evolution'
    | '/api/webhooks/meta'
    | '/campanhas'
    | '/api/campaigns/$id/contacts'
    | '/api/campaigns/$id/schedule'
    | '/api/campaigns/worker/tick'
    | '/api/companies/$id/subscription'
    | '/api/conversations/$id/assume'
    | '/api/conversations/$id/messages'
    | '/api/conversations/$id/read'
    | '/api/conversations/$id/transfer'
    | '/api/evolution/channels/$id'
    | '/api/messages/$messageId/media'
    | '/api/messages/send/evolution'
    | '/api/meta/channels/$id'
    | '/api/public/webhooks/evolution'
    | '/api/public/webhooks/meta'
    | '/api/webhooks/meta/whatsapp'
    | '/api/campaigns/$id/contacts/$contactRowId'
    | '/api/evolution/channels/$id/connect'
    | '/api/evolution/channels/$id/disconnect'
    | '/api/evolution/channels/$id/qrcode'
    | '/api/evolution/channels/$id/status'
    | '/api/internal-chat/messages/$id/attachment'
    | '/api/messages/send/media/evolution'
    | '/api/meta/channels/$id/status'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/atendimento'
    | '/_app/automacoes'
    | '/_app/campanhas'
    | '/_app/canais'
    | '/_app/comunicacao-interna'
    | '/_app/configuracoes'
    | '/_app/contatos'
    | '/_app/dashboard'
    | '/_app/empresas'
    | '/_app/grupos-internos'
    | '/_app/logs'
    | '/_app/usuarios'
    | '/api/attendants'
    | '/api/campaigns'
    | '/api/companies'
    | '/api/contacts'
    | '/api/conversations'
    | '/api/dashboard'
    | '/api/messages'
    | '/api/plans'
    | '/api/users'
    | '/webhook/evolution'
    | '/_app/campanhas/$id'
    | '/_app/campanhas/nova'
    | '/api/admin/auth-check'
    | '/api/admin/reset-password'
    | '/api/admin/seed-demo'
    | '/api/attendance/notifications'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/auth/operational-company'
    | '/api/auth/register'
    | '/api/campaigns/$id'
    | '/api/companies/$id'
    | '/api/contacts/$id'
    | '/api/conversations/start'
    | '/api/dashboard/campaigns'
    | '/api/debug/cols'
    | '/api/debug/current-user'
    | '/api/debug/db'
    | '/api/debug/plans-selects'
    | '/api/evolution/channels'
    | '/api/evolution/register-channel'
    | '/api/evolution/schema-check'
    | '/api/evolution/status'
    | '/api/internal-chat/create'
    | '/api/internal-chat/list'
    | '/api/internal-chat/mark-read'
    | '/api/internal-chat/messages'
    | '/api/internal-chat/send'
    | '/api/internal-chat/unread-count'
    | '/api/internal-chat/users'
    | '/api/meta/channels'
    | '/api/users/$id'
    | '/api/webhooks/evolution'
    | '/api/webhooks/meta'
    | '/_app/campanhas/'
    | '/api/campaigns/$id/contacts'
    | '/api/campaigns/$id/schedule'
    | '/api/campaigns/worker/tick'
    | '/api/companies/$id/subscription'
    | '/api/conversations/$id/assume'
    | '/api/conversations/$id/messages'
    | '/api/conversations/$id/read'
    | '/api/conversations/$id/transfer'
    | '/api/evolution/channels/$id'
    | '/api/messages/$messageId/media'
    | '/api/messages/send/evolution'
    | '/api/meta/channels/$id'
    | '/api/public/webhooks/evolution'
    | '/api/public/webhooks/meta'
    | '/api/webhooks/meta/whatsapp'
    | '/api/campaigns/$id/contacts/$contactRowId'
    | '/api/evolution/channels/$id/connect'
    | '/api/evolution/channels/$id/disconnect'
    | '/api/evolution/channels/$id/qrcode'
    | '/api/evolution/channels/$id/status'
    | '/api/internal-chat/messages/$id/attachment'
    | '/api/messages/send/media/evolution'
    | '/api/meta/channels/$id/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiAttendantsRoute: typeof ApiAttendantsRoute
  ApiCampaignsRoute: typeof ApiCampaignsRouteWithChildren
  ApiCompaniesRoute: typeof ApiCompaniesRouteWithChildren
  ApiContactsRoute: typeof ApiContactsRouteWithChildren
  ApiConversationsRoute: typeof ApiConversationsRouteWithChildren
  ApiDashboardRoute: typeof ApiDashboardRouteWithChildren
  ApiMessagesRoute: typeof ApiMessagesRouteWithChildren
  ApiPlansRoute: typeof ApiPlansRoute
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  WebhookEvolutionRoute: typeof WebhookEvolutionRoute
  ApiAdminAuthCheckRoute: typeof ApiAdminAuthCheckRoute
  ApiAdminResetPasswordRoute: typeof ApiAdminResetPasswordRoute
  ApiAdminSeedDemoRoute: typeof ApiAdminSeedDemoRoute
  ApiAttendanceNotificationsRoute: typeof ApiAttendanceNotificationsRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthOperationalCompanyRoute: typeof ApiAuthOperationalCompanyRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiDebugColsRoute: typeof ApiDebugColsRoute
  ApiDebugCurrentUserRoute: typeof ApiDebugCurrentUserRoute
  ApiDebugDbRoute: typeof ApiDebugDbRoute
  ApiDebugPlansSelectsRoute: typeof ApiDebugPlansSelectsRoute
  ApiEvolutionChannelsRoute: typeof ApiEvolutionChannelsRouteWithChildren
  ApiEvolutionRegisterChannelRoute: typeof ApiEvolutionRegisterChannelRoute
  ApiEvolutionSchemaCheckRoute: typeof ApiEvolutionSchemaCheckRoute
  ApiEvolutionStatusRoute: typeof ApiEvolutionStatusRoute
  ApiInternalChatCreateRoute: typeof ApiInternalChatCreateRoute
  ApiInternalChatListRoute: typeof ApiInternalChatListRoute
  ApiInternalChatMarkReadRoute: typeof ApiInternalChatMarkReadRoute
  ApiInternalChatMessagesRoute: typeof ApiInternalChatMessagesRouteWithChildren
  ApiInternalChatSendRoute: typeof ApiInternalChatSendRoute
  ApiInternalChatUnreadCountRoute: typeof ApiInternalChatUnreadCountRoute
  ApiInternalChatUsersRoute: typeof ApiInternalChatUsersRoute
  ApiMetaChannelsRoute: typeof ApiMetaChannelsRouteWithChildren
  ApiWebhooksEvolutionRoute: typeof ApiWebhooksEvolutionRoute
  ApiWebhooksMetaRoute: typeof ApiWebhooksMetaRouteWithChildren
  ApiPublicWebhooksEvolutionRoute: typeof ApiPublicWebhooksEvolutionRoute
  ApiPublicWebhooksMetaRoute: typeof ApiPublicWebhooksMetaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhook/evolution': {
      id: '/webhook/evolution'
      path: '/webhook/evolution'
      fullPath: '/webhook/evolution'
      preLoaderRoute: typeof WebhookEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plans': {
      id: '/api/plans'
      path: '/api/plans'
      fullPath: '/api/plans'
      preLoaderRoute: typeof ApiPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages': {
      id: '/api/messages'
      path: '/api/messages'
      fullPath: '/api/messages'
      preLoaderRoute: typeof ApiMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard': {
      id: '/api/dashboard'
      path: '/api/dashboard'
      fullPath: '/api/dashboard'
      preLoaderRoute: typeof ApiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations': {
      id: '/api/conversations'
      path: '/api/conversations'
      fullPath: '/api/conversations'
      preLoaderRoute: typeof ApiConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contacts': {
      id: '/api/contacts'
      path: '/api/contacts'
      fullPath: '/api/contacts'
      preLoaderRoute: typeof ApiContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/companies': {
      id: '/api/companies'
      path: '/api/companies'
      fullPath: '/api/companies'
      preLoaderRoute: typeof ApiCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns': {
      id: '/api/campaigns'
      path: '/api/campaigns'
      fullPath: '/api/campaigns'
      preLoaderRoute: typeof ApiCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attendants': {
      id: '/api/attendants'
      path: '/api/attendants'
      fullPath: '/api/attendants'
      preLoaderRoute: typeof ApiAttendantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grupos-internos': {
      id: '/_app/grupos-internos'
      path: '/grupos-internos'
      fullPath: '/grupos-internos'
      preLoaderRoute: typeof AppGruposInternosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empresas': {
      id: '/_app/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AppEmpresasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contatos': {
      id: '/_app/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof AppContatosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comunicacao-interna': {
      id: '/_app/comunicacao-interna'
      path: '/comunicacao-interna'
      fullPath: '/comunicacao-interna'
      preLoaderRoute: typeof AppComunicacaoInternaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/canais': {
      id: '/_app/canais'
      path: '/canais'
      fullPath: '/canais'
      preLoaderRoute: typeof AppCanaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campanhas': {
      id: '/_app/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof AppCampanhasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automacoes': {
      id: '/_app/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AppAutomacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/atendimento': {
      id: '/_app/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AppAtendimentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campanhas/': {
      id: '/_app/campanhas/'
      path: '/'
      fullPath: '/campanhas/'
      preLoaderRoute: typeof AppCampanhasIndexRouteImport
      parentRoute: typeof AppCampanhasRoute
    }
    '/api/webhooks/meta': {
      id: '/api/webhooks/meta'
      path: '/api/webhooks/meta'
      fullPath: '/api/webhooks/meta'
      preLoaderRoute: typeof ApiWebhooksMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/evolution': {
      id: '/api/webhooks/evolution'
      path: '/api/webhooks/evolution'
      fullPath: '/api/webhooks/evolution'
      preLoaderRoute: typeof ApiWebhooksEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/meta/channels': {
      id: '/api/meta/channels'
      path: '/api/meta/channels'
      fullPath: '/api/meta/channels'
      preLoaderRoute: typeof ApiMetaChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal-chat/users': {
      id: '/api/internal-chat/users'
      path: '/api/internal-chat/users'
      fullPath: '/api/internal-chat/users'
      preLoaderRoute: typeof ApiInternalChatUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal-chat/unread-count': {
      id: '/api/internal-chat/unread-count'
      path: '/api/internal-chat/unread-count'
      fullPath: '/api/internal-chat/unread-count'
      preLoaderRoute: typeof ApiInternalChatUnreadCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal-chat/send': {
      id: '/api/internal-chat/send'
      path: '/api/internal-chat/send'
      fullPath: '/api/internal-chat/send'
      preLoaderRoute: typeof ApiInternalChatSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal-chat/messages': {
      id: '/api/internal-chat/messages'
      path: '/api/internal-chat/messages'
      fullPath: '/api/internal-chat/messages'
      preLoaderRoute: typeof ApiInternalChatMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal-chat/mark-read': {
      id: '/api/internal-chat/mark-read'
      path: '/api/internal-chat/mark-read'
      fullPath: '/api/internal-chat/mark-read'
      preLoaderRoute: typeof ApiInternalChatMarkReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal-chat/list': {
      id: '/api/internal-chat/list'
      path: '/api/internal-chat/list'
      fullPath: '/api/internal-chat/list'
      preLoaderRoute: typeof ApiInternalChatListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal-chat/create': {
      id: '/api/internal-chat/create'
      path: '/api/internal-chat/create'
      fullPath: '/api/internal-chat/create'
      preLoaderRoute: typeof ApiInternalChatCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evolution/status': {
      id: '/api/evolution/status'
      path: '/api/evolution/status'
      fullPath: '/api/evolution/status'
      preLoaderRoute: typeof ApiEvolutionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evolution/schema-check': {
      id: '/api/evolution/schema-check'
      path: '/api/evolution/schema-check'
      fullPath: '/api/evolution/schema-check'
      preLoaderRoute: typeof ApiEvolutionSchemaCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evolution/register-channel': {
      id: '/api/evolution/register-channel'
      path: '/api/evolution/register-channel'
      fullPath: '/api/evolution/register-channel'
      preLoaderRoute: typeof ApiEvolutionRegisterChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evolution/channels': {
      id: '/api/evolution/channels'
      path: '/api/evolution/channels'
      fullPath: '/api/evolution/channels'
      preLoaderRoute: typeof ApiEvolutionChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/plans-selects': {
      id: '/api/debug/plans-selects'
      path: '/api/debug/plans-selects'
      fullPath: '/api/debug/plans-selects'
      preLoaderRoute: typeof ApiDebugPlansSelectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/db': {
      id: '/api/debug/db'
      path: '/api/debug/db'
      fullPath: '/api/debug/db'
      preLoaderRoute: typeof ApiDebugDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/current-user': {
      id: '/api/debug/current-user'
      path: '/api/debug/current-user'
      fullPath: '/api/debug/current-user'
      preLoaderRoute: typeof ApiDebugCurrentUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/cols': {
      id: '/api/debug/cols'
      path: '/api/debug/cols'
      fullPath: '/api/debug/cols'
      preLoaderRoute: typeof ApiDebugColsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/campaigns': {
      id: '/api/dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/api/dashboard/campaigns'
      preLoaderRoute: typeof ApiDashboardCampaignsRouteImport
      parentRoute: typeof ApiDashboardRoute
    }
    '/api/conversations/start': {
      id: '/api/conversations/start'
      path: '/start'
      fullPath: '/api/conversations/start'
      preLoaderRoute: typeof ApiConversationsStartRouteImport
      parentRoute: typeof ApiConversationsRoute
    }
    '/api/contacts/$id': {
      id: '/api/contacts/$id'
      path: '/$id'
      fullPath: '/api/contacts/$id'
      preLoaderRoute: typeof ApiContactsIdRouteImport
      parentRoute: typeof ApiContactsRoute
    }
    '/api/companies/$id': {
      id: '/api/companies/$id'
      path: '/$id'
      fullPath: '/api/companies/$id'
      preLoaderRoute: typeof ApiCompaniesIdRouteImport
      parentRoute: typeof ApiCompaniesRoute
    }
    '/api/campaigns/$id': {
      id: '/api/campaigns/$id'
      path: '/$id'
      fullPath: '/api/campaigns/$id'
      preLoaderRoute: typeof ApiCampaignsIdRouteImport
      parentRoute: typeof ApiCampaignsRoute
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/operational-company': {
      id: '/api/auth/operational-company'
      path: '/api/auth/operational-company'
      fullPath: '/api/auth/operational-company'
      preLoaderRoute: typeof ApiAuthOperationalCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attendance/notifications': {
      id: '/api/attendance/notifications'
      path: '/api/attendance/notifications'
      fullPath: '/api/attendance/notifications'
      preLoaderRoute: typeof ApiAttendanceNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/seed-demo': {
      id: '/api/admin/seed-demo'
      path: '/api/admin/seed-demo'
      fullPath: '/api/admin/seed-demo'
      preLoaderRoute: typeof ApiAdminSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reset-password': {
      id: '/api/admin/reset-password'
      path: '/api/admin/reset-password'
      fullPath: '/api/admin/reset-password'
      preLoaderRoute: typeof ApiAdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth-check': {
      id: '/api/admin/auth-check'
      path: '/api/admin/auth-check'
      fullPath: '/api/admin/auth-check'
      preLoaderRoute: typeof ApiAdminAuthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/campanhas/nova': {
      id: '/_app/campanhas/nova'
      path: '/nova'
      fullPath: '/campanhas/nova'
      preLoaderRoute: typeof AppCampanhasNovaRouteImport
      parentRoute: typeof AppCampanhasRoute
    }
    '/_app/campanhas/$id': {
      id: '/_app/campanhas/$id'
      path: '/$id'
      fullPath: '/campanhas/$id'
      preLoaderRoute: typeof AppCampanhasIdRouteImport
      parentRoute: typeof AppCampanhasRoute
    }
    '/api/webhooks/meta/whatsapp': {
      id: '/api/webhooks/meta/whatsapp'
      path: '/whatsapp'
      fullPath: '/api/webhooks/meta/whatsapp'
      preLoaderRoute: typeof ApiWebhooksMetaWhatsappRouteImport
      parentRoute: typeof ApiWebhooksMetaRoute
    }
    '/api/public/webhooks/meta': {
      id: '/api/public/webhooks/meta'
      path: '/api/public/webhooks/meta'
      fullPath: '/api/public/webhooks/meta'
      preLoaderRoute: typeof ApiPublicWebhooksMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/evolution': {
      id: '/api/public/webhooks/evolution'
      path: '/api/public/webhooks/evolution'
      fullPath: '/api/public/webhooks/evolution'
      preLoaderRoute: typeof ApiPublicWebhooksEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/channels/$id': {
      id: '/api/meta/channels/$id'
      path: '/$id'
      fullPath: '/api/meta/channels/$id'
      preLoaderRoute: typeof ApiMetaChannelsIdRouteImport
      parentRoute: typeof ApiMetaChannelsRoute
    }
    '/api/messages/send/evolution': {
      id: '/api/messages/send/evolution'
      path: '/send/evolution'
      fullPath: '/api/messages/send/evolution'
      preLoaderRoute: typeof ApiMessagesSendEvolutionRouteImport
      parentRoute: typeof ApiMessagesRoute
    }
    '/api/messages/$messageId/media': {
      id: '/api/messages/$messageId/media'
      path: '/$messageId/media'
      fullPath: '/api/messages/$messageId/media'
      preLoaderRoute: typeof ApiMessagesMessageIdMediaRouteImport
      parentRoute: typeof ApiMessagesRoute
    }
    '/api/evolution/channels/$id': {
      id: '/api/evolution/channels/$id'
      path: '/$id'
      fullPath: '/api/evolution/channels/$id'
      preLoaderRoute: typeof ApiEvolutionChannelsIdRouteImport
      parentRoute: typeof ApiEvolutionChannelsRoute
    }
    '/api/conversations/$id/transfer': {
      id: '/api/conversations/$id/transfer'
      path: '/$id/transfer'
      fullPath: '/api/conversations/$id/transfer'
      preLoaderRoute: typeof ApiConversationsIdTransferRouteImport
      parentRoute: typeof ApiConversationsRoute
    }
    '/api/conversations/$id/read': {
      id: '/api/conversations/$id/read'
      path: '/$id/read'
      fullPath: '/api/conversations/$id/read'
      preLoaderRoute: typeof ApiConversationsIdReadRouteImport
      parentRoute: typeof ApiConversationsRoute
    }
    '/api/conversations/$id/messages': {
      id: '/api/conversations/$id/messages'
      path: '/$id/messages'
      fullPath: '/api/conversations/$id/messages'
      preLoaderRoute: typeof ApiConversationsIdMessagesRouteImport
      parentRoute: typeof ApiConversationsRoute
    }
    '/api/conversations/$id/assume': {
      id: '/api/conversations/$id/assume'
      path: '/$id/assume'
      fullPath: '/api/conversations/$id/assume'
      preLoaderRoute: typeof ApiConversationsIdAssumeRouteImport
      parentRoute: typeof ApiConversationsRoute
    }
    '/api/companies/$id/subscription': {
      id: '/api/companies/$id/subscription'
      path: '/subscription'
      fullPath: '/api/companies/$id/subscription'
      preLoaderRoute: typeof ApiCompaniesIdSubscriptionRouteImport
      parentRoute: typeof ApiCompaniesIdRoute
    }
    '/api/campaigns/worker/tick': {
      id: '/api/campaigns/worker/tick'
      path: '/worker/tick'
      fullPath: '/api/campaigns/worker/tick'
      preLoaderRoute: typeof ApiCampaignsWorkerTickRouteImport
      parentRoute: typeof ApiCampaignsRoute
    }
    '/api/campaigns/$id/schedule': {
      id: '/api/campaigns/$id/schedule'
      path: '/schedule'
      fullPath: '/api/campaigns/$id/schedule'
      preLoaderRoute: typeof ApiCampaignsIdScheduleRouteImport
      parentRoute: typeof ApiCampaignsIdRoute
    }
    '/api/campaigns/$id/contacts': {
      id: '/api/campaigns/$id/contacts'
      path: '/contacts'
      fullPath: '/api/campaigns/$id/contacts'
      preLoaderRoute: typeof ApiCampaignsIdContactsRouteImport
      parentRoute: typeof ApiCampaignsIdRoute
    }
    '/api/meta/channels/$id/status': {
      id: '/api/meta/channels/$id/status'
      path: '/status'
      fullPath: '/api/meta/channels/$id/status'
      preLoaderRoute: typeof ApiMetaChannelsIdStatusRouteImport
      parentRoute: typeof ApiMetaChannelsIdRoute
    }
    '/api/messages/send/media/evolution': {
      id: '/api/messages/send/media/evolution'
      path: '/send/media/evolution'
      fullPath: '/api/messages/send/media/evolution'
      preLoaderRoute: typeof ApiMessagesSendMediaEvolutionRouteImport
      parentRoute: typeof ApiMessagesRoute
    }
    '/api/internal-chat/messages/$id/attachment': {
      id: '/api/internal-chat/messages/$id/attachment'
      path: '/$id/attachment'
      fullPath: '/api/internal-chat/messages/$id/attachment'
      preLoaderRoute: typeof ApiInternalChatMessagesIdAttachmentRouteImport
      parentRoute: typeof ApiInternalChatMessagesRoute
    }
    '/api/evolution/channels/$id/status': {
      id: '/api/evolution/channels/$id/status'
      path: '/status'
      fullPath: '/api/evolution/channels/$id/status'
      preLoaderRoute: typeof ApiEvolutionChannelsIdStatusRouteImport
      parentRoute: typeof ApiEvolutionChannelsIdRoute
    }
    '/api/evolution/channels/$id/qrcode': {
      id: '/api/evolution/channels/$id/qrcode'
      path: '/qrcode'
      fullPath: '/api/evolution/channels/$id/qrcode'
      preLoaderRoute: typeof ApiEvolutionChannelsIdQrcodeRouteImport
      parentRoute: typeof ApiEvolutionChannelsIdRoute
    }
    '/api/evolution/channels/$id/disconnect': {
      id: '/api/evolution/channels/$id/disconnect'
      path: '/disconnect'
      fullPath: '/api/evolution/channels/$id/disconnect'
      preLoaderRoute: typeof ApiEvolutionChannelsIdDisconnectRouteImport
      parentRoute: typeof ApiEvolutionChannelsIdRoute
    }
    '/api/evolution/channels/$id/connect': {
      id: '/api/evolution/channels/$id/connect'
      path: '/connect'
      fullPath: '/api/evolution/channels/$id/connect'
      preLoaderRoute: typeof ApiEvolutionChannelsIdConnectRouteImport
      parentRoute: typeof ApiEvolutionChannelsIdRoute
    }
    '/api/campaigns/$id/contacts/$contactRowId': {
      id: '/api/campaigns/$id/contacts/$contactRowId'
      path: '/$contactRowId'
      fullPath: '/api/campaigns/$id/contacts/$contactRowId'
      preLoaderRoute: typeof ApiCampaignsIdContactsContactRowIdRouteImport
      parentRoute: typeof ApiCampaignsIdContactsRoute
    }
  }
}

interface AppCampanhasRouteChildren {
  AppCampanhasIdRoute: typeof AppCampanhasIdRoute
  AppCampanhasNovaRoute: typeof AppCampanhasNovaRoute
  AppCampanhasIndexRoute: typeof AppCampanhasIndexRoute
}

const AppCampanhasRouteChildren: AppCampanhasRouteChildren = {
  AppCampanhasIdRoute: AppCampanhasIdRoute,
  AppCampanhasNovaRoute: AppCampanhasNovaRoute,
  AppCampanhasIndexRoute: AppCampanhasIndexRoute,
}

const AppCampanhasRouteWithChildren = AppCampanhasRoute._addFileChildren(
  AppCampanhasRouteChildren,
)

interface AppRouteChildren {
  AppAtendimentoRoute: typeof AppAtendimentoRoute
  AppAutomacoesRoute: typeof AppAutomacoesRoute
  AppCampanhasRoute: typeof AppCampanhasRouteWithChildren
  AppCanaisRoute: typeof AppCanaisRoute
  AppComunicacaoInternaRoute: typeof AppComunicacaoInternaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContatosRoute: typeof AppContatosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmpresasRoute: typeof AppEmpresasRoute
  AppGruposInternosRoute: typeof AppGruposInternosRoute
  AppLogsRoute: typeof AppLogsRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAtendimentoRoute: AppAtendimentoRoute,
  AppAutomacoesRoute: AppAutomacoesRoute,
  AppCampanhasRoute: AppCampanhasRouteWithChildren,
  AppCanaisRoute: AppCanaisRoute,
  AppComunicacaoInternaRoute: AppComunicacaoInternaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContatosRoute: AppContatosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmpresasRoute: AppEmpresasRoute,
  AppGruposInternosRoute: AppGruposInternosRoute,
  AppLogsRoute: AppLogsRoute,
  AppUsuariosRoute: AppUsuariosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiCampaignsIdContactsRouteChildren {
  ApiCampaignsIdContactsContactRowIdRoute: typeof ApiCampaignsIdContactsContactRowIdRoute
}

const ApiCampaignsIdContactsRouteChildren: ApiCampaignsIdContactsRouteChildren =
  {
    ApiCampaignsIdContactsContactRowIdRoute:
      ApiCampaignsIdContactsContactRowIdRoute,
  }

const ApiCampaignsIdContactsRouteWithChildren =
  ApiCampaignsIdContactsRoute._addFileChildren(
    ApiCampaignsIdContactsRouteChildren,
  )

interface ApiCampaignsIdRouteChildren {
  ApiCampaignsIdContactsRoute: typeof ApiCampaignsIdContactsRouteWithChildren
  ApiCampaignsIdScheduleRoute: typeof ApiCampaignsIdScheduleRoute
}

const ApiCampaignsIdRouteChildren: ApiCampaignsIdRouteChildren = {
  ApiCampaignsIdContactsRoute: ApiCampaignsIdContactsRouteWithChildren,
  ApiCampaignsIdScheduleRoute: ApiCampaignsIdScheduleRoute,
}

const ApiCampaignsIdRouteWithChildren = ApiCampaignsIdRoute._addFileChildren(
  ApiCampaignsIdRouteChildren,
)

interface ApiCampaignsRouteChildren {
  ApiCampaignsIdRoute: typeof ApiCampaignsIdRouteWithChildren
  ApiCampaignsWorkerTickRoute: typeof ApiCampaignsWorkerTickRoute
}

const ApiCampaignsRouteChildren: ApiCampaignsRouteChildren = {
  ApiCampaignsIdRoute: ApiCampaignsIdRouteWithChildren,
  ApiCampaignsWorkerTickRoute: ApiCampaignsWorkerTickRoute,
}

const ApiCampaignsRouteWithChildren = ApiCampaignsRoute._addFileChildren(
  ApiCampaignsRouteChildren,
)

interface ApiCompaniesIdRouteChildren {
  ApiCompaniesIdSubscriptionRoute: typeof ApiCompaniesIdSubscriptionRoute
}

const ApiCompaniesIdRouteChildren: ApiCompaniesIdRouteChildren = {
  ApiCompaniesIdSubscriptionRoute: ApiCompaniesIdSubscriptionRoute,
}

const ApiCompaniesIdRouteWithChildren = ApiCompaniesIdRoute._addFileChildren(
  ApiCompaniesIdRouteChildren,
)

interface ApiCompaniesRouteChildren {
  ApiCompaniesIdRoute: typeof ApiCompaniesIdRouteWithChildren
}

const ApiCompaniesRouteChildren: ApiCompaniesRouteChildren = {
  ApiCompaniesIdRoute: ApiCompaniesIdRouteWithChildren,
}

const ApiCompaniesRouteWithChildren = ApiCompaniesRoute._addFileChildren(
  ApiCompaniesRouteChildren,
)

interface ApiContactsRouteChildren {
  ApiContactsIdRoute: typeof ApiContactsIdRoute
}

const ApiContactsRouteChildren: ApiContactsRouteChildren = {
  ApiContactsIdRoute: ApiContactsIdRoute,
}

const ApiContactsRouteWithChildren = ApiContactsRoute._addFileChildren(
  ApiContactsRouteChildren,
)

interface ApiConversationsRouteChildren {
  ApiConversationsStartRoute: typeof ApiConversationsStartRoute
  ApiConversationsIdAssumeRoute: typeof ApiConversationsIdAssumeRoute
  ApiConversationsIdMessagesRoute: typeof ApiConversationsIdMessagesRoute
  ApiConversationsIdReadRoute: typeof ApiConversationsIdReadRoute
  ApiConversationsIdTransferRoute: typeof ApiConversationsIdTransferRoute
}

const ApiConversationsRouteChildren: ApiConversationsRouteChildren = {
  ApiConversationsStartRoute: ApiConversationsStartRoute,
  ApiConversationsIdAssumeRoute: ApiConversationsIdAssumeRoute,
  ApiConversationsIdMessagesRoute: ApiConversationsIdMessagesRoute,
  ApiConversationsIdReadRoute: ApiConversationsIdReadRoute,
  ApiConversationsIdTransferRoute: ApiConversationsIdTransferRoute,
}

const ApiConversationsRouteWithChildren =
  ApiConversationsRoute._addFileChildren(ApiConversationsRouteChildren)

interface ApiDashboardRouteChildren {
  ApiDashboardCampaignsRoute: typeof ApiDashboardCampaignsRoute
}

const ApiDashboardRouteChildren: ApiDashboardRouteChildren = {
  ApiDashboardCampaignsRoute: ApiDashboardCampaignsRoute,
}

const ApiDashboardRouteWithChildren = ApiDashboardRoute._addFileChildren(
  ApiDashboardRouteChildren,
)

interface ApiMessagesRouteChildren {
  ApiMessagesMessageIdMediaRoute: typeof ApiMessagesMessageIdMediaRoute
  ApiMessagesSendEvolutionRoute: typeof ApiMessagesSendEvolutionRoute
  ApiMessagesSendMediaEvolutionRoute: typeof ApiMessagesSendMediaEvolutionRoute
}

const ApiMessagesRouteChildren: ApiMessagesRouteChildren = {
  ApiMessagesMessageIdMediaRoute: ApiMessagesMessageIdMediaRoute,
  ApiMessagesSendEvolutionRoute: ApiMessagesSendEvolutionRoute,
  ApiMessagesSendMediaEvolutionRoute: ApiMessagesSendMediaEvolutionRoute,
}

const ApiMessagesRouteWithChildren = ApiMessagesRoute._addFileChildren(
  ApiMessagesRouteChildren,
)

interface ApiUsersRouteChildren {
  ApiUsersIdRoute: typeof ApiUsersIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersIdRoute: ApiUsersIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

interface ApiEvolutionChannelsIdRouteChildren {
  ApiEvolutionChannelsIdConnectRoute: typeof ApiEvolutionChannelsIdConnectRoute
  ApiEvolutionChannelsIdDisconnectRoute: typeof ApiEvolutionChannelsIdDisconnectRoute
  ApiEvolutionChannelsIdQrcodeRoute: typeof ApiEvolutionChannelsIdQrcodeRoute
  ApiEvolutionChannelsIdStatusRoute: typeof ApiEvolutionChannelsIdStatusRoute
}

const ApiEvolutionChannelsIdRouteChildren: ApiEvolutionChannelsIdRouteChildren =
  {
    ApiEvolutionChannelsIdConnectRoute: ApiEvolutionChannelsIdConnectRoute,
    ApiEvolutionChannelsIdDisconnectRoute:
      ApiEvolutionChannelsIdDisconnectRoute,
    ApiEvolutionChannelsIdQrcodeRoute: ApiEvolutionChannelsIdQrcodeRoute,
    ApiEvolutionChannelsIdStatusRoute: ApiEvolutionChannelsIdStatusRoute,
  }

const ApiEvolutionChannelsIdRouteWithChildren =
  ApiEvolutionChannelsIdRoute._addFileChildren(
    ApiEvolutionChannelsIdRouteChildren,
  )

interface ApiEvolutionChannelsRouteChildren {
  ApiEvolutionChannelsIdRoute: typeof ApiEvolutionChannelsIdRouteWithChildren
}

const ApiEvolutionChannelsRouteChildren: ApiEvolutionChannelsRouteChildren = {
  ApiEvolutionChannelsIdRoute: ApiEvolutionChannelsIdRouteWithChildren,
}

const ApiEvolutionChannelsRouteWithChildren =
  ApiEvolutionChannelsRoute._addFileChildren(ApiEvolutionChannelsRouteChildren)

interface ApiInternalChatMessagesRouteChildren {
  ApiInternalChatMessagesIdAttachmentRoute: typeof ApiInternalChatMessagesIdAttachmentRoute
}

const ApiInternalChatMessagesRouteChildren: ApiInternalChatMessagesRouteChildren =
  {
    ApiInternalChatMessagesIdAttachmentRoute:
      ApiInternalChatMessagesIdAttachmentRoute,
  }

const ApiInternalChatMessagesRouteWithChildren =
  ApiInternalChatMessagesRoute._addFileChildren(
    ApiInternalChatMessagesRouteChildren,
  )

interface ApiMetaChannelsIdRouteChildren {
  ApiMetaChannelsIdStatusRoute: typeof ApiMetaChannelsIdStatusRoute
}

const ApiMetaChannelsIdRouteChildren: ApiMetaChannelsIdRouteChildren = {
  ApiMetaChannelsIdStatusRoute: ApiMetaChannelsIdStatusRoute,
}

const ApiMetaChannelsIdRouteWithChildren =
  ApiMetaChannelsIdRoute._addFileChildren(ApiMetaChannelsIdRouteChildren)

interface ApiMetaChannelsRouteChildren {
  ApiMetaChannelsIdRoute: typeof ApiMetaChannelsIdRouteWithChildren
}

const ApiMetaChannelsRouteChildren: ApiMetaChannelsRouteChildren = {
  ApiMetaChannelsIdRoute: ApiMetaChannelsIdRouteWithChildren,
}

const ApiMetaChannelsRouteWithChildren = ApiMetaChannelsRoute._addFileChildren(
  ApiMetaChannelsRouteChildren,
)

interface ApiWebhooksMetaRouteChildren {
  ApiWebhooksMetaWhatsappRoute: typeof ApiWebhooksMetaWhatsappRoute
}

const ApiWebhooksMetaRouteChildren: ApiWebhooksMetaRouteChildren = {
  ApiWebhooksMetaWhatsappRoute: ApiWebhooksMetaWhatsappRoute,
}

const ApiWebhooksMetaRouteWithChildren = ApiWebhooksMetaRoute._addFileChildren(
  ApiWebhooksMetaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiAttendantsRoute: ApiAttendantsRoute,
  ApiCampaignsRoute: ApiCampaignsRouteWithChildren,
  ApiCompaniesRoute: ApiCompaniesRouteWithChildren,
  ApiContactsRoute: ApiContactsRouteWithChildren,
  ApiConversationsRoute: ApiConversationsRouteWithChildren,
  ApiDashboardRoute: ApiDashboardRouteWithChildren,
  ApiMessagesRoute: ApiMessagesRouteWithChildren,
  ApiPlansRoute: ApiPlansRoute,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  WebhookEvolutionRoute: WebhookEvolutionRoute,
  ApiAdminAuthCheckRoute: ApiAdminAuthCheckRoute,
  ApiAdminResetPasswordRoute: ApiAdminResetPasswordRoute,
  ApiAdminSeedDemoRoute: ApiAdminSeedDemoRoute,
  ApiAttendanceNotificationsRoute: ApiAttendanceNotificationsRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthOperationalCompanyRoute: ApiAuthOperationalCompanyRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiDebugColsRoute: ApiDebugColsRoute,
  ApiDebugCurrentUserRoute: ApiDebugCurrentUserRoute,
  ApiDebugDbRoute: ApiDebugDbRoute,
  ApiDebugPlansSelectsRoute: ApiDebugPlansSelectsRoute,
  ApiEvolutionChannelsRoute: ApiEvolutionChannelsRouteWithChildren,
  ApiEvolutionRegisterChannelRoute: ApiEvolutionRegisterChannelRoute,
  ApiEvolutionSchemaCheckRoute: ApiEvolutionSchemaCheckRoute,
  ApiEvolutionStatusRoute: ApiEvolutionStatusRoute,
  ApiInternalChatCreateRoute: ApiInternalChatCreateRoute,
  ApiInternalChatListRoute: ApiInternalChatListRoute,
  ApiInternalChatMarkReadRoute: ApiInternalChatMarkReadRoute,
  ApiInternalChatMessagesRoute: ApiInternalChatMessagesRouteWithChildren,
  ApiInternalChatSendRoute: ApiInternalChatSendRoute,
  ApiInternalChatUnreadCountRoute: ApiInternalChatUnreadCountRoute,
  ApiInternalChatUsersRoute: ApiInternalChatUsersRoute,
  ApiMetaChannelsRoute: ApiMetaChannelsRouteWithChildren,
  ApiWebhooksEvolutionRoute: ApiWebhooksEvolutionRoute,
  ApiWebhooksMetaRoute: ApiWebhooksMetaRouteWithChildren,
  ApiPublicWebhooksEvolutionRoute: ApiPublicWebhooksEvolutionRoute,
  ApiPublicWebhooksMetaRoute: ApiPublicWebhooksMetaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
