/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WebhookEvolutionRouteImport } from './routes/webhook/evolution'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiMessagesRouteImport } from './routes/api/messages'
import { Route as AppUsuariosRouteImport } from './routes/_app.usuarios'
import { Route as AppLogsRouteImport } from './routes/_app.logs'
import { Route as AppGruposInternosRouteImport } from './routes/_app.grupos-internos'
import { Route as AppEmpresasRouteImport } from './routes/_app.empresas'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppContatosRouteImport } from './routes/_app.contatos'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppComunicacaoInternaRouteImport } from './routes/_app.comunicacao-interna'
import { Route as AppCanaisRouteImport } from './routes/_app.canais'
import { Route as AppAutomacoesRouteImport } from './routes/_app.automacoes'
import { Route as AppAtendimentoRouteImport } from './routes/_app.atendimento'
import { Route as ApiUsersIdRouteImport } from './routes/api/users/$id'
import { Route as ApiInternalChatUsersRouteImport } from './routes/api/internal-chat/users'
import { Route as ApiInternalChatSendRouteImport } from './routes/api/internal-chat/send'
import { Route as ApiInternalChatMessagesRouteImport } from './routes/api/internal-chat/messages'
import { Route as ApiInternalChatListRouteImport } from './routes/api/internal-chat/list'
import { Route as ApiInternalChatCreateRouteImport } from './routes/api/internal-chat/create'
import { Route as ApiDebugDbRouteImport } from './routes/api/debug/db'
import { Route as ApiDebugCurrentUserRouteImport } from './routes/api/debug/current-user'
import { Route as ApiDebugColsRouteImport } from './routes/api/debug/cols'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth/register'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAdminSeedDemoRouteImport } from './routes/api/admin/seed-demo'
import { Route as ApiAdminAuthCheckRouteImport } from './routes/api/admin/auth-check'
import { Route as ApiPublicWebhooksEvolutionRouteImport } from './routes/api/public/webhooks/evolution'
import { Route as ApiMessagesMessageIdMediaRouteImport } from './routes/api/messages/$messageId/media'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebhookEvolutionRoute = WebhookEvolutionRouteImport.update({
  id: '/webhook/evolution',
  path: '/webhook/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesRoute = ApiMessagesRouteImport.update({
  id: '/api/messages',
  path: '/api/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppGruposInternosRoute = AppGruposInternosRouteImport.update({
  id: '/grupos-internos',
  path: '/grupos-internos',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresasRoute = AppEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppContatosRoute = AppContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppComunicacaoInternaRoute = AppComunicacaoInternaRouteImport.update({
  id: '/comunicacao-interna',
  path: '/comunicacao-interna',
  getParentRoute: () => AppRoute,
} as any)
const AppCanaisRoute = AppCanaisRouteImport.update({
  id: '/canais',
  path: '/canais',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomacoesRoute = AppAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAtendimentoRoute = AppAtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => AppRoute,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiInternalChatUsersRoute = ApiInternalChatUsersRouteImport.update({
  id: '/api/internal-chat/users',
  path: '/api/internal-chat/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalChatSendRoute = ApiInternalChatSendRouteImport.update({
  id: '/api/internal-chat/send',
  path: '/api/internal-chat/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalChatMessagesRoute = ApiInternalChatMessagesRouteImport.update({
  id: '/api/internal-chat/messages',
  path: '/api/internal-chat/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalChatListRoute = ApiInternalChatListRouteImport.update({
  id: '/api/internal-chat/list',
  path: '/api/internal-chat/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalChatCreateRoute = ApiInternalChatCreateRouteImport.update({
  id: '/api/internal-chat/create',
  path: '/api/internal-chat/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugDbRoute = ApiDebugDbRouteImport.update({
  id: '/api/debug/db',
  path: '/api/debug/db',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugCurrentUserRoute = ApiDebugCurrentUserRouteImport.update({
  id: '/api/debug/current-user',
  path: '/api/debug/current-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugColsRoute = ApiDebugColsRouteImport.update({
  id: '/api/debug/cols',
  path: '/api/debug/cols',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSeedDemoRoute = ApiAdminSeedDemoRouteImport.update({
  id: '/api/admin/seed-demo',
  path: '/api/admin/seed-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthCheckRoute = ApiAdminAuthCheckRouteImport.update({
  id: '/api/admin/auth-check',
  path: '/api/admin/auth-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksEvolutionRoute =
  ApiPublicWebhooksEvolutionRouteImport.update({
    id: '/api/public/webhooks/evolution',
    path: '/api/public/webhooks/evolution',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMessagesMessageIdMediaRoute =
  ApiMessagesMessageIdMediaRouteImport.update({
    id: '/$messageId/media',
    path: '/$messageId/media',
    getParentRoute: () => ApiMessagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/atendimento': typeof AppAtendimentoRoute
  '/automacoes': typeof AppAutomacoesRoute
  '/canais': typeof AppCanaisRoute
  '/comunicacao-interna': typeof AppComunicacaoInternaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contatos': typeof AppContatosRoute
  '/dashboard': typeof AppDashboardRoute
  '/empresas': typeof AppEmpresasRoute
  '/grupos-internos': typeof AppGruposInternosRoute
  '/logs': typeof AppLogsRoute
  '/usuarios': typeof AppUsuariosRoute
  '/api/messages': typeof ApiMessagesRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/webhook/evolution': typeof WebhookEvolutionRoute
  '/api/admin/auth-check': typeof ApiAdminAuthCheckRoute
  '/api/admin/seed-demo': typeof ApiAdminSeedDemoRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/debug/cols': typeof ApiDebugColsRoute
  '/api/debug/current-user': typeof ApiDebugCurrentUserRoute
  '/api/debug/db': typeof ApiDebugDbRoute
  '/api/internal-chat/create': typeof ApiInternalChatCreateRoute
  '/api/internal-chat/list': typeof ApiInternalChatListRoute
  '/api/internal-chat/messages': typeof ApiInternalChatMessagesRoute
  '/api/internal-chat/send': typeof ApiInternalChatSendRoute
  '/api/internal-chat/users': typeof ApiInternalChatUsersRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/messages/$messageId/media': typeof ApiMessagesMessageIdMediaRoute
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/atendimento': typeof AppAtendimentoRoute
  '/automacoes': typeof AppAutomacoesRoute
  '/canais': typeof AppCanaisRoute
  '/comunicacao-interna': typeof AppComunicacaoInternaRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/contatos': typeof AppContatosRoute
  '/dashboard': typeof AppDashboardRoute
  '/empresas': typeof AppEmpresasRoute
  '/grupos-internos': typeof AppGruposInternosRoute
  '/logs': typeof AppLogsRoute
  '/usuarios': typeof AppUsuariosRoute
  '/api/messages': typeof ApiMessagesRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/webhook/evolution': typeof WebhookEvolutionRoute
  '/api/admin/auth-check': typeof ApiAdminAuthCheckRoute
  '/api/admin/seed-demo': typeof ApiAdminSeedDemoRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/debug/cols': typeof ApiDebugColsRoute
  '/api/debug/current-user': typeof ApiDebugCurrentUserRoute
  '/api/debug/db': typeof ApiDebugDbRoute
  '/api/internal-chat/create': typeof ApiInternalChatCreateRoute
  '/api/internal-chat/list': typeof ApiInternalChatListRoute
  '/api/internal-chat/messages': typeof ApiInternalChatMessagesRoute
  '/api/internal-chat/send': typeof ApiInternalChatSendRoute
  '/api/internal-chat/users': typeof ApiInternalChatUsersRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/messages/$messageId/media': typeof ApiMessagesMessageIdMediaRoute
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/atendimento': typeof AppAtendimentoRoute
  '/_app/automacoes': typeof AppAutomacoesRoute
  '/_app/canais': typeof AppCanaisRoute
  '/_app/comunicacao-interna': typeof AppComunicacaoInternaRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/contatos': typeof AppContatosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/empresas': typeof AppEmpresasRoute
  '/_app/grupos-internos': typeof AppGruposInternosRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/api/messages': typeof ApiMessagesRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/webhook/evolution': typeof WebhookEvolutionRoute
  '/api/admin/auth-check': typeof ApiAdminAuthCheckRoute
  '/api/admin/seed-demo': typeof ApiAdminSeedDemoRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/debug/cols': typeof ApiDebugColsRoute
  '/api/debug/current-user': typeof ApiDebugCurrentUserRoute
  '/api/debug/db': typeof ApiDebugDbRoute
  '/api/internal-chat/create': typeof ApiInternalChatCreateRoute
  '/api/internal-chat/list': typeof ApiInternalChatListRoute
  '/api/internal-chat/messages': typeof ApiInternalChatMessagesRoute
  '/api/internal-chat/send': typeof ApiInternalChatSendRoute
  '/api/internal-chat/users': typeof ApiInternalChatUsersRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/messages/$messageId/media': typeof ApiMessagesMessageIdMediaRoute
  '/api/public/webhooks/evolution': typeof ApiPublicWebhooksEvolutionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/atendimento'
    | '/automacoes'
    | '/canais'
    | '/comunicacao-interna'
    | '/configuracoes'
    | '/contatos'
    | '/dashboard'
    | '/empresas'
    | '/grupos-internos'
    | '/logs'
    | '/usuarios'
    | '/api/messages'
    | '/api/users'
    | '/webhook/evolution'
    | '/api/admin/auth-check'
    | '/api/admin/seed-demo'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/debug/cols'
    | '/api/debug/current-user'
    | '/api/debug/db'
    | '/api/internal-chat/create'
    | '/api/internal-chat/list'
    | '/api/internal-chat/messages'
    | '/api/internal-chat/send'
    | '/api/internal-chat/users'
    | '/api/users/$id'
    | '/api/messages/$messageId/media'
    | '/api/public/webhooks/evolution'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/atendimento'
    | '/automacoes'
    | '/canais'
    | '/comunicacao-interna'
    | '/configuracoes'
    | '/contatos'
    | '/dashboard'
    | '/empresas'
    | '/grupos-internos'
    | '/logs'
    | '/usuarios'
    | '/api/messages'
    | '/api/users'
    | '/webhook/evolution'
    | '/api/admin/auth-check'
    | '/api/admin/seed-demo'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/debug/cols'
    | '/api/debug/current-user'
    | '/api/debug/db'
    | '/api/internal-chat/create'
    | '/api/internal-chat/list'
    | '/api/internal-chat/messages'
    | '/api/internal-chat/send'
    | '/api/internal-chat/users'
    | '/api/users/$id'
    | '/api/messages/$messageId/media'
    | '/api/public/webhooks/evolution'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/atendimento'
    | '/_app/automacoes'
    | '/_app/canais'
    | '/_app/comunicacao-interna'
    | '/_app/configuracoes'
    | '/_app/contatos'
    | '/_app/dashboard'
    | '/_app/empresas'
    | '/_app/grupos-internos'
    | '/_app/logs'
    | '/_app/usuarios'
    | '/api/messages'
    | '/api/users'
    | '/webhook/evolution'
    | '/api/admin/auth-check'
    | '/api/admin/seed-demo'
    | '/api/auth/login'
    | '/api/auth/me'
    | '/api/auth/register'
    | '/api/debug/cols'
    | '/api/debug/current-user'
    | '/api/debug/db'
    | '/api/internal-chat/create'
    | '/api/internal-chat/list'
    | '/api/internal-chat/messages'
    | '/api/internal-chat/send'
    | '/api/internal-chat/users'
    | '/api/users/$id'
    | '/api/messages/$messageId/media'
    | '/api/public/webhooks/evolution'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiMessagesRoute: typeof ApiMessagesRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  WebhookEvolutionRoute: typeof WebhookEvolutionRoute
  ApiAdminAuthCheckRoute: typeof ApiAdminAuthCheckRoute
  ApiAdminSeedDemoRoute: typeof ApiAdminSeedDemoRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiDebugColsRoute: typeof ApiDebugColsRoute
  ApiDebugCurrentUserRoute: typeof ApiDebugCurrentUserRoute
  ApiDebugDbRoute: typeof ApiDebugDbRoute
  ApiInternalChatCreateRoute: typeof ApiInternalChatCreateRoute
  ApiInternalChatListRoute: typeof ApiInternalChatListRoute
  ApiInternalChatMessagesRoute: typeof ApiInternalChatMessagesRoute
  ApiInternalChatSendRoute: typeof ApiInternalChatSendRoute
  ApiInternalChatUsersRoute: typeof ApiInternalChatUsersRoute
  ApiPublicWebhooksEvolutionRoute: typeof ApiPublicWebhooksEvolutionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webhook/evolution': {
      id: '/webhook/evolution'
      path: '/webhook/evolution'
      fullPath: '/webhook/evolution'
      preLoaderRoute: typeof WebhookEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages': {
      id: '/api/messages'
      path: '/api/messages'
      fullPath: '/api/messages'
      preLoaderRoute: typeof ApiMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grupos-internos': {
      id: '/_app/grupos-internos'
      path: '/grupos-internos'
      fullPath: '/grupos-internos'
      preLoaderRoute: typeof AppGruposInternosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empresas': {
      id: '/_app/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AppEmpresasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contatos': {
      id: '/_app/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof AppContatosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comunicacao-interna': {
      id: '/_app/comunicacao-interna'
      path: '/comunicacao-interna'
      fullPath: '/comunicacao-interna'
      preLoaderRoute: typeof AppComunicacaoInternaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/canais': {
      id: '/_app/canais'
      path: '/canais'
      fullPath: '/canais'
      preLoaderRoute: typeof AppCanaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automacoes': {
      id: '/_app/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AppAutomacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/atendimento': {
      id: '/_app/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AppAtendimentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/internal-chat/users': {
      id: '/api/internal-chat/users'
      path: '/api/internal-chat/users'
      fullPath: '/api/internal-chat/users'
      preLoaderRoute: typeof ApiInternalChatUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal-chat/send': {
      id: '/api/internal-chat/send'
      path: '/api/internal-chat/send'
      fullPath: '/api/internal-chat/send'
      preLoaderRoute: typeof ApiInternalChatSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal-chat/messages': {
      id: '/api/internal-chat/messages'
      path: '/api/internal-chat/messages'
      fullPath: '/api/internal-chat/messages'
      preLoaderRoute: typeof ApiInternalChatMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal-chat/list': {
      id: '/api/internal-chat/list'
      path: '/api/internal-chat/list'
      fullPath: '/api/internal-chat/list'
      preLoaderRoute: typeof ApiInternalChatListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal-chat/create': {
      id: '/api/internal-chat/create'
      path: '/api/internal-chat/create'
      fullPath: '/api/internal-chat/create'
      preLoaderRoute: typeof ApiInternalChatCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/db': {
      id: '/api/debug/db'
      path: '/api/debug/db'
      fullPath: '/api/debug/db'
      preLoaderRoute: typeof ApiDebugDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/current-user': {
      id: '/api/debug/current-user'
      path: '/api/debug/current-user'
      fullPath: '/api/debug/current-user'
      preLoaderRoute: typeof ApiDebugCurrentUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/cols': {
      id: '/api/debug/cols'
      path: '/api/debug/cols'
      fullPath: '/api/debug/cols'
      preLoaderRoute: typeof ApiDebugColsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/seed-demo': {
      id: '/api/admin/seed-demo'
      path: '/api/admin/seed-demo'
      fullPath: '/api/admin/seed-demo'
      preLoaderRoute: typeof ApiAdminSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth-check': {
      id: '/api/admin/auth-check'
      path: '/api/admin/auth-check'
      fullPath: '/api/admin/auth-check'
      preLoaderRoute: typeof ApiAdminAuthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/evolution': {
      id: '/api/public/webhooks/evolution'
      path: '/api/public/webhooks/evolution'
      fullPath: '/api/public/webhooks/evolution'
      preLoaderRoute: typeof ApiPublicWebhooksEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages/$messageId/media': {
      id: '/api/messages/$messageId/media'
      path: '/$messageId/media'
      fullPath: '/api/messages/$messageId/media'
      preLoaderRoute: typeof ApiMessagesMessageIdMediaRouteImport
      parentRoute: typeof ApiMessagesRoute
    }
  }
}

interface AppRouteChildren {
  AppAtendimentoRoute: typeof AppAtendimentoRoute
  AppAutomacoesRoute: typeof AppAutomacoesRoute
  AppCanaisRoute: typeof AppCanaisRoute
  AppComunicacaoInternaRoute: typeof AppComunicacaoInternaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContatosRoute: typeof AppContatosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEmpresasRoute: typeof AppEmpresasRoute
  AppGruposInternosRoute: typeof AppGruposInternosRoute
  AppLogsRoute: typeof AppLogsRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAtendimentoRoute: AppAtendimentoRoute,
  AppAutomacoesRoute: AppAutomacoesRoute,
  AppCanaisRoute: AppCanaisRoute,
  AppComunicacaoInternaRoute: AppComunicacaoInternaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContatosRoute: AppContatosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEmpresasRoute: AppEmpresasRoute,
  AppGruposInternosRoute: AppGruposInternosRoute,
  AppLogsRoute: AppLogsRoute,
  AppUsuariosRoute: AppUsuariosRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiMessagesRouteChildren {
  ApiMessagesMessageIdMediaRoute: typeof ApiMessagesMessageIdMediaRoute
}

const ApiMessagesRouteChildren: ApiMessagesRouteChildren = {
  ApiMessagesMessageIdMediaRoute: ApiMessagesMessageIdMediaRoute,
}

const ApiMessagesRouteWithChildren = ApiMessagesRoute._addFileChildren(
  ApiMessagesRouteChildren,
)

interface ApiUsersRouteChildren {
  ApiUsersIdRoute: typeof ApiUsersIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersIdRoute: ApiUsersIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiMessagesRoute: ApiMessagesRouteWithChildren,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  WebhookEvolutionRoute: WebhookEvolutionRoute,
  ApiAdminAuthCheckRoute: ApiAdminAuthCheckRoute,
  ApiAdminSeedDemoRoute: ApiAdminSeedDemoRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiDebugColsRoute: ApiDebugColsRoute,
  ApiDebugCurrentUserRoute: ApiDebugCurrentUserRoute,
  ApiDebugDbRoute: ApiDebugDbRoute,
  ApiInternalChatCreateRoute: ApiInternalChatCreateRoute,
  ApiInternalChatListRoute: ApiInternalChatListRoute,
  ApiInternalChatMessagesRoute: ApiInternalChatMessagesRoute,
  ApiInternalChatSendRoute: ApiInternalChatSendRoute,
  ApiInternalChatUsersRoute: ApiInternalChatUsersRoute,
  ApiPublicWebhooksEvolutionRoute: ApiPublicWebhooksEvolutionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
